#!/bin/bash

function createOrgpt() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/orgpt.demosk.org/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/orgpt.demosk.org/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:7054 --caname ca-orgpt --tls.certfiles "${PWD}/organizations/fabric-ca/orgpt/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-orgpt.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-orgpt.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-orgpt.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-orgpt.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/orgpt.demosk.org/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy orgpt's CA cert to orgpt's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/orgpt.demosk.org/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/orgpt/ca-cert.pem" "${PWD}/organizations/peerOrganizations/orgpt.demosk.org/msp/tlscacerts/ca.crt"

  # Copy orgpt's CA cert to orgpt's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/orgpt.demosk.org/tlsca"
  cp "${PWD}/organizations/fabric-ca/orgpt/ca-cert.pem" "${PWD}/organizations/peerOrganizations/orgpt.demosk.org/tlsca/tlsca.orgpt.demosk.org-cert.pem"

  # Copy orgpt's CA cert to orgpt's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/orgpt.demosk.org/ca"
  cp "${PWD}/organizations/fabric-ca/orgpt/ca-cert.pem" "${PWD}/organizations/peerOrganizations/orgpt.demosk.org/ca/ca.orgpt.demosk.org-cert.pem"

  infoln "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-orgpt --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/orgpt/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname ca-orgpt --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/orgpt/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-orgpt --id.name orgptadmin --id.secret orgptadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/orgpt/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-orgpt -M "${PWD}/organizations/peerOrganizations/orgpt.demosk.org/peers/peer0.orgpt.demosk.org/msp" --csr.hosts peer0.orgpt.demosk.org --tls.certfiles "${PWD}/organizations/fabric-ca/orgpt/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/orgpt.demosk.org/msp/config.yaml" "${PWD}/organizations/peerOrganizations/orgpt.demosk.org/peers/peer0.orgpt.demosk.org/msp/config.yaml"

  infoln "Generating the peer0-tls certificates"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-orgpt -M "${PWD}/organizations/peerOrganizations/orgpt.demosk.org/peers/peer0.orgpt.demosk.org/tls" --enrollment.profile tls --csr.hosts peer0.orgpt.demosk.org --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/orgpt/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/orgpt.demosk.org/peers/peer0.orgpt.demosk.org/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/orgpt.demosk.org/peers/peer0.orgpt.demosk.org/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/orgpt.demosk.org/peers/peer0.orgpt.demosk.org/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/orgpt.demosk.org/peers/peer0.orgpt.demosk.org/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/orgpt.demosk.org/peers/peer0.orgpt.demosk.org/tls/keystore/"* "${PWD}/organizations/peerOrganizations/orgpt.demosk.org/peers/peer0.orgpt.demosk.org/tls/server.key"

  infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:7054 --caname ca-orgpt -M "${PWD}/organizations/peerOrganizations/orgpt.demosk.org/users/User1@orgpt.demosk.org/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/orgpt/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/orgpt.demosk.org/msp/config.yaml" "${PWD}/organizations/peerOrganizations/orgpt.demosk.org/users/User1@orgpt.demosk.org/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://orgptadmin:orgptadminpw@localhost:7054 --caname ca-orgpt -M "${PWD}/organizations/peerOrganizations/orgpt.demosk.org/users/Admin@orgpt.demosk.org/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/orgpt/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/orgpt.demosk.org/msp/config.yaml" "${PWD}/organizations/peerOrganizations/orgpt.demosk.org/users/Admin@orgpt.demosk.org/msp/config.yaml"
}

function createOrderer() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/ordererOrganizations/demosk.org

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/ordererOrganizations/demosk.org

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:9054 --caname ca-orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/ordererOrganizations/demosk.org/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy orderer org's CA cert to orderer org's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/demosk.org/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/demosk.org/msp/tlscacerts/tlsca.demosk.org-cert.pem"

  # Copy orderer org's CA cert to orderer org's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/ordererOrganizations/demosk.org/tlsca"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/demosk.org/tlsca/tlsca.demosk.org-cert.pem"

  infoln "Registering orderer"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name orderer --id.secret ordererpw --id.type orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the orderer admin"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name ordererAdmin --id.secret ordererAdminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the orderer msp"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/demosk.org/orderers/ordererpt.demosk.org/msp" --csr.hosts ordererpt.demosk.org --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/demosk.org/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/demosk.org/orderers/ordererpt.demosk.org/msp/config.yaml"

  infoln "Generating the orderer-tls certificates"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/demosk.org/orderers/ordererpt.demosk.org/tls" --enrollment.profile tls --csr.hosts ordererpt.demosk.org --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the orderer's tls directory that are referenced by orderer startup config
  cp "${PWD}/organizations/ordererOrganizations/demosk.org/orderers/ordererpt.demosk.org/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/demosk.org/orderers/ordererpt.demosk.org/tls/ca.crt"
  cp "${PWD}/organizations/ordererOrganizations/demosk.org/orderers/ordererpt.demosk.org/tls/signcerts/"* "${PWD}/organizations/ordererOrganizations/demosk.org/orderers/ordererpt.demosk.org/tls/server.crt"
  cp "${PWD}/organizations/ordererOrganizations/demosk.org/orderers/ordererpt.demosk.org/tls/keystore/"* "${PWD}/organizations/ordererOrganizations/demosk.org/orderers/ordererpt.demosk.org/tls/server.key"

  # Copy orderer org's CA cert to orderer's /msp/tlscacerts directory (for use in the orderer MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/demosk.org/orderers/ordererpt.demosk.org/msp/tlscacerts"
  cp "${PWD}/organizations/ordererOrganizations/demosk.org/orderers/ordererpt.demosk.org/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/demosk.org/orderers/ordererpt.demosk.org/msp/tlscacerts/tlsca.demosk.org-cert.pem"

  infoln "Generating the admin msp"
  set -x
  fabric-ca-client enroll -u https://ordererAdmin:ordererAdminpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/demosk.org/users/Admin@demosk.org/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/demosk.org/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/demosk.org/users/Admin@demosk.org/msp/config.yaml"
}
